Repository COS301-SE-2022/Training-Buddy, pull requests merged in 2022-10, with the labels that each got.

#461 💅Fix mobile logos
  apps/client/src/assets/icons/icon-128x128.png
  apps/client/src/assets/icons/icon-144x144.png
  apps/client/src/assets/icons/icon-152x152.png
  apps/client/src/assets/icons/icon-192x192.png
  apps/client/src/assets/icons/icon-384x384.png
  apps/client/src/assets/icons/icon-512x512.png
  apps/client/src/assets/icons/icon-72x72.png
  apps/client/src/assets/icons/icon-96x96.png
  apps/client/src/manifest.webmanifest
Labels: priority:low, scope:ui, status:ready, type:enhance

#462 📝 (ReadMe): Update readme
  README.md
  profileimages/derived.png
  profileimages/epiuse.png
Labels: priority:high, priority:medium, scope:repository, scope:ui, status:ready, type:change, type:documentation, type:enhance, type:new

#463 💯 (Video): Project day video
  README.md
Labels: priority:high, priority:medium, scope:repository, status:ready, type:bug, type:change, type:documentation, type:enhance, type:new
