Repository COS301-SE-2022/Training-Buddy, pull requests merged in 2022-08, with the labels that each got.

#321 💚fix CI/CD tests
  .github/workflows/PRmetatest.yml
  .github/workflows/full.yml
  .github/workflows/index.yml
Labels: priority:high, scope:cicd, status:ready, type:enhance

#324 Fixes and additions
  libs/api/internal-api/repository/data-access/src/lib/api-internal-api-repository-data-access.service.ts
Labels: priority:medium, scope:db, status:ready, type:change, type:enhance, type:new

#325 ✨ GETTING WORKOUT HISTORY
  libs/api/internal-api/api/shared/interfaces/data-access/src/lib/user.entity.ts
  libs/api/internal-api/api/training-buddy-api/src/lib/training-buddy-api.resolver.ts
  libs/api/internal-api/service/training-buddy-service/src/lib/training-buddy-service.service.ts
Labels: priority:medium, scope:api, status:ready, type:enhance

#326 :art: Adding query for strava client side
  libs/client/strava/feature/src/lib/services/strava-api.service.ts
Labels: priority:low, scope:client, status:not-ready, type:change

#328 ✨Workout History UI
  libs/api/internal-api/repository/data-access/src/lib/api-internal-api-repository-data-access.service.ts
  libs/client/schedule/feature/src/lib/viewschedule/viewschedule.component.html
  libs/client/schedule/feature/src/lib/viewschedule/viewschedule.component.scss
  libs/client/schedule/feature/src/lib/viewschedule/viewschedule.component.ts
Labels: priority:medium, scope:client, status:ready, type:new

#340 Rating system
  libs/client/schedule/feature/src/lib/client-schedule-feature.module.ts
  libs/client/schedule/feature/src/lib/rating/rating.component.html
  libs/client/schedule/feature/src/lib/rating/rating.component.scss
  libs/client/schedule/feature/src/lib/rating/rating.component.spec.ts
  libs/client/schedule/feature/src/lib/rating/rating.component.ts
  libs/client/schedule/feature/src/lib/workout/workout.component.html
  libs/client/schedule/feature/src/lib/workout/workout.component.ts
Labels: priority:high, scope:ui, status:ready, status:needs-tests, type:enhance, scope:admin

#337 Sign Up Stages and Some Strava additions
  apps/api/src/main.ts
  libs/api/internal-api/api/shared/interfaces/data-access/src/lib/tokens.ts
  libs/api/internal-api/api/training-buddy-api/src/lib/training-buddy-api.resolver.ts
  libs/api/internal-api/repository/data-access/src/lib/api-internal-api-repository-data-access.service.ts
  libs/api/internal-api/service/training-buddy-service/src/lib/training-buddy-service.service.spec.ts
  libs/api/internal-api/service/training-buddy-service/src/lib/training-buddy-service.service.ts
  libs/client/strava/feature/src/lib/services/strava-api.service.ts
Labels: priority:medium, scope:db, status:ready, type:enhance

#344 Add success message
  libs/client/login/feature/src/lib/loginpage/loginpage.component.html
  libs/client/schedule/feature/src/lib/rating/rating.component.html
  libs/client/schedule/feature/src/lib/rating/rating.component.spec.ts
  libs/client/schedule/feature/src/lib/rating/rating.component.ts
Labels: priority:low, scope:api, scope:ui, status:ready, type:enhance

#338 🚀 Deployment
  .gitignore
  apps/api/project.json
  apps/api/src/main.ts
  apps/client/project.json
  apps/client/proxy.conf.json
  apps/client/src/app/app.module.ts
  database-debug.log
  database.rules.json
  firebase.json
  firestore-debug.log
  firestore.indexes.json
  firestore.rules
  package.json
  public/index.html
  remoteconfig.template.json
  storage.rules
Labels: priority:high, scope:api, scope:cicd, scope:client, scope:db, scope:repository, scope:ui, status:ready, type:enhance, scope:admin, type:new
